### ISSUE TITLE
Rename `MockServiceProvider::addDefinition()` to `setDefinition()`

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii-testing#8]
Seems, `setDefinition()` will be more logical, because definition can be overrided.

**Comment by alien-art** [comment]
Going to fix this

**Comment by samdark** [comment]
Seems to be renamed already: https://github.com/yiisoft/yii-testing/blob/21eead563a806417bc446ce859df4a6c484bef4c/src/MockServiceProvider.php#L24
